MODEL (
  name interim.stock_info,
  kind SCD_TYPE_2_BY_TIME (
    unique_key symbol,
    updated_at_name _dlt_load_time
  ),
  grain (
    symbol
  ),
  audits (
    NOT_NULL(columns = (
      symbol
    ))
  ),
  cron '@daily'
);

SELECT
  address1::TEXT AS address1,
  city::TEXT AS city,
  state::TEXT AS state,
  zip::TEXT AS zip,
  country::TEXT AS country,
  phone::TEXT AS phone,
  website::TEXT AS website,
  industry::TEXT AS industry,
  industry_key::TEXT AS industry_key,
  industry_disp::TEXT AS industry_disp,
  sector::TEXT AS sector,
  sector_key::TEXT AS sector_key,
  sector_disp::TEXT AS sector_disp,
  long_business_summary::TEXT AS long_business_summary,
  full_time_employees::BIGINT AS full_time_employees,
  audit_risk::BIGINT AS audit_risk,
  board_risk::BIGINT AS board_risk,
  compensation_risk::BIGINT AS compensation_risk,
  share_holder_rights_risk::BIGINT AS share_holder_rights_risk,
  overall_risk::BIGINT AS overall_risk,
  governance_epoch_date::BIGINT AS governance_epoch_date,
  compensation_as_of_epoch_date::BIGINT AS compensation_as_of_epoch_date,
  ir_website::TEXT AS ir_website,
  max_age::BIGINT AS max_age,
  price_hint::BIGINT AS price_hint,
  previous_close::DOUBLE AS previous_close,
  open::DOUBLE AS open,
  day_low::DOUBLE AS day_low,
  day_high::DOUBLE AS day_high,
  regular_market_previous_close::DOUBLE AS regular_market_previous_close,
  regular_market_open::DOUBLE AS regular_market_open,
  regular_market_day_low::DOUBLE AS regular_market_day_low,
  regular_market_day_high::DOUBLE AS regular_market_day_high,
  dividend_rate::DOUBLE AS dividend_rate,
  dividend_yield::DOUBLE AS dividend_yield,
  ex_dividend_date::BIGINT AS ex_dividend_date,
  payout_ratio::DOUBLE AS payout_ratio,
  five_year_avg_dividend_yield::DOUBLE AS five_year_avg_dividend_yield,
  beta::DOUBLE AS beta,
  trailing_pe::DOUBLE AS trailing_pe,
  forward_pe::DOUBLE AS forward_pe,
  volume::BIGINT AS volume,
  regular_market_volume::BIGINT AS regular_market_volume,
  average_volume::BIGINT AS average_volume,
  average_volume10days::BIGINT AS average_volume10days,
  average_daily_volume10_day::BIGINT AS average_daily_volume10_day,
  bid::DOUBLE AS bid,
  ask::DOUBLE AS ask,
  bid_size::BIGINT AS bid_size,
  ask_size::BIGINT AS ask_size,
  market_cap::BIGINT AS market_cap,
  fifty_two_week_low::DOUBLE AS fifty_two_week_low,
  fifty_two_week_high::DOUBLE AS fifty_two_week_high,
  price_to_sales_trailing12_months::DOUBLE AS price_to_sales_trailing12_months,
  fifty_day_average::DOUBLE AS fifty_day_average,
  two_hundred_day_average::DOUBLE AS two_hundred_day_average,
  trailing_annual_dividend_rate::DOUBLE AS trailing_annual_dividend_rate,
  trailing_annual_dividend_yield::DOUBLE AS trailing_annual_dividend_yield,
  currency::TEXT AS currency,
  enterprise_value::BIGINT AS enterprise_value,
  profit_margins::DOUBLE AS profit_margins,
  float_shares::BIGINT AS float_shares,
  shares_outstanding::BIGINT AS shares_outstanding,
  shares_short::BIGINT AS shares_short,
  shares_short_prior_month::BIGINT AS shares_short_prior_month,
  shares_short_previous_month_date::BIGINT AS shares_short_previous_month_date,
  date_short_interest::BIGINT AS date_short_interest,
  shares_percent_shares_out::DOUBLE AS shares_percent_shares_out,
  held_percent_insiders::DOUBLE AS held_percent_insiders,
  held_percent_institutions::DOUBLE AS held_percent_institutions,
  short_ratio::DOUBLE AS short_ratio,
  short_percent_of_float::DOUBLE AS short_percent_of_float,
  implied_shares_outstanding::BIGINT AS implied_shares_outstanding,
  book_value::DOUBLE AS book_value,
  price_to_book::DOUBLE AS price_to_book,
  last_fiscal_year_end::BIGINT AS last_fiscal_year_end,
  next_fiscal_year_end::BIGINT AS next_fiscal_year_end,
  most_recent_quarter::BIGINT AS most_recent_quarter,
  earnings_quarterly_growth::DOUBLE AS earnings_quarterly_growth,
  net_income_to_common::BIGINT AS net_income_to_common,
  trailing_eps::DOUBLE AS trailing_eps,
  forward_eps::DOUBLE AS forward_eps,
  last_split_factor::TEXT AS last_split_factor,
  last_split_date::BIGINT AS last_split_date,
  enterprise_to_revenue::DOUBLE AS enterprise_to_revenue,
  enterprise_to_ebitda::DOUBLE AS enterprise_to_ebitda,
  _52_week_change::DOUBLE AS _52_week_change,
  sand_p52_week_change::DOUBLE AS sand_p52_week_change,
  last_dividend_value::DOUBLE AS last_dividend_value,
  last_dividend_date::BIGINT AS last_dividend_date,
  exchange::TEXT AS exchange,
  quote_type::TEXT AS quote_type,
  symbol::TEXT AS symbol,
  underlying_symbol::TEXT AS underlying_symbol,
  short_name::TEXT AS short_name,
  long_name::TEXT AS long_name,
  first_trade_date_epoch_utc::BIGINT AS first_trade_date_epoch_utc,
  time_zone_full_name::TEXT AS time_zone_full_name,
  time_zone_short_name::TEXT AS time_zone_short_name,
  uuid::TEXT AS uuid,
  message_board_id::TEXT AS message_board_id,
  gmt_off_set_milliseconds::BIGINT AS gmt_off_set_milliseconds,
  current_price::DOUBLE AS current_price,
  target_high_price::DOUBLE AS target_high_price,
  target_low_price::DOUBLE AS target_low_price,
  target_mean_price::DOUBLE AS target_mean_price,
  target_median_price::DOUBLE AS target_median_price,
  recommendation_mean::DOUBLE AS recommendation_mean,
  recommendation_key::TEXT AS recommendation_key,
  number_of_analyst_opinions::BIGINT AS number_of_analyst_opinions,
  total_cash::BIGINT AS total_cash,
  total_cash_per_share::DOUBLE AS total_cash_per_share,
  ebitda::BIGINT AS ebitda,
  total_debt::BIGINT AS total_debt,
  quick_ratio::DOUBLE AS quick_ratio,
  current_ratio::DOUBLE AS current_ratio,
  total_revenue::BIGINT AS total_revenue,
  debt_to_equity::DOUBLE AS debt_to_equity,
  revenue_per_share::DOUBLE AS revenue_per_share,
  return_on_assets::DOUBLE AS return_on_assets,
  return_on_equity::DOUBLE AS return_on_equity,
  free_cashflow::BIGINT AS free_cashflow,
  operating_cashflow::BIGINT AS operating_cashflow,
  earnings_growth::DOUBLE AS earnings_growth,
  revenue_growth::DOUBLE AS revenue_growth,
  gross_margins::DOUBLE AS gross_margins,
  ebitda_margins::DOUBLE AS ebitda_margins,
  operating_margins::DOUBLE AS operating_margins,
  financial_currency::TEXT AS financial_currency,
  trailing_peg_ratio::DOUBLE AS trailing_peg_ratio,
  _dlt_load_id::TEXT AS _dlt_load_id,
  _dlt_id::TEXT AS _dlt_id,
  TO_TIMESTAMP(_dlt_load_id::DOUBLE) AS _dlt_load_time
FROM stock_data.stock_info