[project]
name = "sqlmesh-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt[duckdb,motherduck]>=1.4.1",
    "duckdb>=1.3.1",
    "sqlmesh[web]>=0.188.1",
    "yfinance>=0.2.61",
]
