dbt_local_ducklake:
  outputs:
    local:
      type: duckdb
      threads: 1

      extensions:
        - ducklake
        - postgres

      secrets:
        - name: ducklake_secret
          type: postgres
          host: localhost
          port: 5432
          database: ducklake_catalog
          
      attach:
        - path: "ducklake:postgres:"
          alias: catalog
          options:
            data_path: data_files
            meta_secret: ducklake_secret

  target: local